---
apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: rchain-coop
spec:
  secretName: tls-letsencrypt-rchain-coop
  commonName: rchain.coop
  dnsNames:
    - rchain.coop
    - www.rchain.coop
    - developer.rchain.coop
    - rsong.rchain.coop
    - blog.rchain.coop
    - dbadmin.rchain.coop
    - faq.rchain.coop

  issuerRef:
    name: rchain-coop
    kind: ClusterIssuer
  acme:
    config:
      - ingressClass: nginx
        domains:
          - rchain.coop
          - www.rchain.coop
          - developer.rchain.coop
          - rsong.rchain.coop
          - blog.rchain.coop
          - dbadmin.rchain.coop
          - faq.rchain.coop
