---
apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: rchain-coop
spec:
  secretName: tls-letsencrypt-rchain-coop
  commonName: rchain.coop
  dnsNames:
    - rchain.coop
    - rchain-coop.cf
    - www.rchain.coop
    - www.rchain-coop.cf
    - developer.rchain.coop
    - forum2.rchain.coop
    - developer.rchain-coop.cf
    - rsong.rchain.coop
    - rsong.rchain-coop.cf
    - blog.rchain-coop.cf
    - blog.rchain.coop
    - dbadmin.rchain.coop
    - dbadmin.rchain-coop.cf
    - dbadmin.rchain-coop.cf

  issuerRef:
    name: rchain-coop
    kind: ClusterIssuer
  acme:
    config:
      - ingressClass: nginx
        domains:
          - rchain.coop
          - rchain-coop.cf
          - www.rchain.coop
          - www.rchain-coop.cf
          - developer.rchain.coop
          - developer.rchain-coop.cf
          - rsong.rchain.coop
          - rsong.rchain-coop.cf
          - blog.rchain.coop 
          - forum2.rchain.coop
          - blog.rchain-coop.cf
          - dbadmin.rchain.coop
          - dbadmin.rchain-coop.cf


